@startuml

left to right direction

skinparam shadowing false
skinparam monochrome true
skinparam Ranksep 100
skinparam Nodesep 50

actor "Editor" as editor <<Unauthenciated>>

rectangle "Elm Todo MVC" as app <<SPA>> {
  usecase "Add Todo" as add_todo
  usecase "Manage List" as manage_list
  usecase "Manage Todo" as manage_todo
}

rectangle "Browser" {
  database "Local Storage" as db
}

editor -- add_todo
editor -- manage_list
editor -- manage_todo

add_todo .> manage_list
manage_list .> manage_todo

add_todo ..> db
manage_list <..> db
manage_todo ..> db

@enduml